#ifndef _DIALOGPROC_H_
#define _DIALOGPROC_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <wtypes.h>


INT_PTR CALLBACK GGenieProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK ColorProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DirectoriesProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK FilesProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK ControllerProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK OptionProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK AboutProc(HWND, UINT, WPARAM, LPARAM);


#ifdef __cplusplus
};
#endif


#endif //_DIALOGPROC_H_